apiVersion: v1
kind: Template
metadata:
  name: vertx-messaging-work-queue-frontend
  annotations:
    tags: vertx, microservice, messaging
    template.openshift.io/provider-display-name: "Red Hat, Inc."
    description: The Vert.x Work Queue Mission demonstrates scalable task processing using messaging
parameters:
- name: SOURCE_REPOSITORY_URL
  description: The source URL for the application
  displayName: Source URL
  value: https://github.com/ssorj/vertx-messaging-work-queue-booster
  required: true
- name: SOURCE_REPOSITORY_REF
  description: The branch name for the application
  displayName: Source Branch
  value: master
  required: true
- name: SOURCE_REPOSITORY_DIR
  description: The location within the source repo of the application
  displayName: Source Directory
  value: frontend
  required: true
- name: GITHUB_WEBHOOK_SECRET
  description: A secret string used to configure the GitHub webhook.
  displayName: GitHub Webhook Secret
  required: true
  from: '[a-zA-Z0-9]{40}'
  generate: expression
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: vertx-messaging-work-queue-frontend
    labels:
      booster: vertx-messaging-work-queue-frontend
  spec: {}
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: runtime-vertx-messaging-work-queue-frontend
    labels:
      booster: vertx-messaging-work-queue-frontend
  spec:
    tags:
    - name: latest
      from:
        kind: DockerImage
        name: registry.access.redhat.com/redhat-openjdk-18/openjdk18-openshift
- apiVersion: v1
  kind: BuildConfig
  metadata:
    name: vertx-messaging-work-queue-frontend
    labels:
      booster: vertx-messaging-work-queue-frontend
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: vertx-messaging-work-queue-frontend:latest
    postCommit: {}
    resources: {}
    source:
      git:
        uri: ${SOURCE_REPOSITORY_URL}
        ref: ${SOURCE_REPOSITORY_REF}
      #contextDir: ${SOURCE_REPOSITORY_DIR}
      type: Git
    strategy:
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: runtime-vertx-messaging-work-queue-frontend:latest
        incremental: true
        env:
        - name: MAVEN_ARGS_APPEND
          value: "-pl ${SOURCE_REPOSITORY_DIR}"
        - name: ARTIFACT_DIR
          value: "${SOURCE_REPOSITORY_DIR}/target"
      type: Source
    triggers:
    - github:
        secret: ${GITHUB_WEBHOOK_SECRET}
      type: GitHub
    - type: ConfigChange
    - imageChange: {}
      type: ImageChange
  status:
    lastVersion: 0
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      fabric8.io/scm-con-url: scm:git:https://github.com/openshiftio/booster-parent.git/vertx-messaging-work-queue-frontend
      prometheus.io/port: "9779"
      fabric8.io/scm-url: https://github.com/openshiftio/vertx-messaging-work-queue-frontend
      fabric8.io/iconUrl: img/icons/vertx.svg
      fabric8.io/git-branch: master
      prometheus.io/scrape: "true"
      fabric8.io/scm-devcon-url: scm:git:git:@github.com:openshiftio/booster-parent.git/vertx-messaging-work-queue-frontend
      fabric8.io/scm-tag: booster-parent-21
    labels:
      expose: "true"
      app: vertx-messaging-work-queue-frontend
      provider: fabric8
      version: 27-SNAPSHOT
      group: io.openshift.booster
    name: vertx-messaging-work-queue-frontend
  spec:
    ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: vertx-messaging-work-queue-frontend
      provider: fabric8
      group: io.openshift.booster
- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    annotations:
      fabric8.io/metrics-path: dashboard/file/kubernetes-pods.json/?var-project=vertx-messaging-work-queue-frontend&var-version=27-SNAPSHOT
      fabric8.io/scm-con-url: scm:git:https://github.com/openshiftio/booster-parent.git/vertx-messaging-work-queue-frontend
      fabric8.io/scm-url: https://github.com/openshiftio/vertx-messaging-work-queue-frontend
      fabric8.io/iconUrl: img/icons/vertx.svg
      fabric8.io/git-branch: master
      fabric8.io/scm-devcon-url: scm:git:git:@github.com:openshiftio/booster-parent.git/vertx-messaging-work-queue-frontend
      fabric8.io/scm-tag: booster-parent-21
    labels:
      app: vertx-messaging-work-queue-frontend
      provider: fabric8
      version: 27-SNAPSHOT
      group: io.openshift.booster
    name: vertx-messaging-work-queue-frontend
  spec:
    replicas: 1
    revisionHistoryLimit: 2
    selector:
      app: vertx-messaging-work-queue-frontend
      provider: fabric8
      group: io.openshift.booster
    strategy:
      rollingParams:
        timeoutSeconds: 3600
      type: Rolling
    template:
      metadata:
        annotations:
          fabric8.io/metrics-path: dashboard/file/kubernetes-pods.json/?var-project=vertx-messaging-work-queue-frontend&var-version=27-SNAPSHOT
          fabric8.io/scm-con-url: scm:git:https://github.com/openshiftio/booster-parent.git/vertx-messaging-work-queue-frontend
          fabric8.io/scm-url: https://github.com/openshiftio/vertx-messaging-work-queue-frontend
          fabric8.io/iconUrl: img/icons/vertx.svg
          fabric8.io/git-branch: master
          fabric8.io/scm-devcon-url: scm:git:git:@github.com:openshiftio/booster-parent.git/vertx-messaging-work-queue-frontend
          fabric8.io/scm-tag: booster-parent-21
        labels:
          app: vertx-messaging-work-queue-frontend
          provider: fabric8
          version: 27-SNAPSHOT
          group: io.openshift.booster
      spec:
        containers:
        - env:
          - name: VERTX_CONFIG_PATH
            value: /deployments/config/app-config.yml
          - name: KUBERNETES_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          image: vertx-messaging-work-queue-frontend:latest
          imagePullPolicy: IfNotPresent
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 180
          name: vertx
          ports:
          - containerPort: 8080
            name: http
            protocol: TCP
          - containerPort: 9779
            name: prometheus
            protocol: TCP
          - containerPort: 8778
            name: jolokia
            protocol: TCP
          readinessProbe:
            httpGet:
              path: /api/health/readiness
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 10
          securityContext:
            privileged: false
          volumeMounts:
          - mountPath: /deployments/config
            name: config
        volumes:
        - configMap:
            items:
            - key: app-config.yml
              path: app-config.yml
            name: app-config
            optional: true
          name: config
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - vertx
        from:
          kind: ImageStreamTag
          name: vertx-messaging-work-queue-frontend:latest
      type: ImageChange
- apiVersion: v1
  kind: Route
  metadata:
    labels:
      app: vertx-messaging-work-queue-frontend
    name: frontend
  spec:
    port:
      targetPort: 8080
    to:
      kind: Service
      name: vertx-messaging-work-queue-frontend
