spec:
  template:
    spec:
      containers:
      - env:
        - name: MESSAGING_SERVICE_HOST
          value: work-queue-broker-amq-amqp
        - name: MESSAGING_SERVICE_PORT
          value: 5672
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 180

